### ISSUE TITLE
CloudOnce Amazon issue

### ISSUE THREAD

**Issue by PixelEnvision** [jizc/CloudOnce#10]
Hi, I'm a CloudOnce customer from the AssetStore days. I wanted to upgrade my project to the latest one from here but I'm having some problems. I'm working on them but that one seems to be coming from the plugin itself.

Import CloudOnce to an empty project, switch to Android platform, fill in google & game circle keys (not sure if that's needed), switch project to Amazon in editor.

Following error logged as soon as I hit save configuration: Assets/Extensions/CloudOnce/Providers/AmazonGameCircle/AmazonCloudProvider.cs(49,15): error CS1729: The type `CloudOnce.Internal.CloudProviderBase<CloudOnce.Internal.Providers.AmazonCloudProvider>' does not contain a constructor that takes `1' arguments

--
- CloudOnce __v2.3.2__
- Unity3D __v5.4.3p3__
- Build platform: Android

**Comment by jizc** [comment]
I see the problem, that's just sloppy on my part. I'll fix it in the next update. For now you can just remove the constructor in the AmazonCloudProvider class. I'm currently waiting for Google to update GPGS for the new social interfaces in Unity 5.5. As soon as they have a new release ready I'll update CloudOnce as well.

**Comment by PixelEnvision** [comment]
@jizc Thanks for the prompt reply!

I've just removed the parameter changing it to the following:
private AmazonCloudProvider()
            : base()
        {
        }

Would that be ok or should I remove the whole constructor?

**Comment by jizc** [comment]
Either is fine, should be no difference.

**Comment by PixelEnvision** [comment]
Just tested it and seems to be working fine, thank you. :)

Btw, will that new update for 5.5 still be backwards compatible with 5.4?

**Comment by jizc** [comment]
Great! It will indeed be backwards compatible.
