### ISSUE TITLE
Android "Run Setup" Error

### ISSUE THREAD

**Issue by PixelEnvision** [jizc/CloudOnce#14]
I've upgraded to latest unity patch (5.5.3p4) which fixes android tools problem and updated android sdk.

Now when I click "Run Setup" it gives the following error, I think that's related to tools location change.

`ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[10.2.6]
Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.GetTransitiveDependencies (System.Collections.Generic.Dictionary`2 dependencies, System.Collections.Generic.List`1 repoPaths)
Google.JarResolver.PlayServicesSupport.FindMissingDependencyPaths (System.String destinationDirectory, System.Collections.Generic.Dictionary`2& dependencyPaths, Google.JarResolver.ExplodeAar explodeAar)
GooglePlayServices.ResolverVer1_1.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
GooglePlayServices.DefaultResolver.DoResolution (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation)
CloudOnce.Internal.Editor.Utils.GPGAndroidSetup.DoSetup (System.String appID) (at Assets/Extensions/CloudOnce/Internal/Editor/Utils/GooglePlayGamesSetup/GPGAndroidSetup.cs:60)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawGooglePlayGamesSetup () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:890)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawSettingsTab () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:767)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawContentArea () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:726)
CloudOnce.Internal.Editor.CloudOnceEditor.OnGUI () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:426)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
`

**Comment by jizc** [comment]
Thank for the heads up, I'm putting together an update that fixes the issue. Should be up within the hour.
