### ISSUE TITLE
DeleteVariable

### ISSUE THREAD

**Issue by PixelEnvision** [jizc/CloudOnce#20]
Hello,

Thanks for the recent update.

I've noticed this earlier too but I forgot to report/ask.

Cloud.Storage.DeleteVariable("key");

This doesn't seems to work, although Cloud.Storage.DeleteAll () works ok. Is this a bug or am I doing something wrong?

--
### Environment

- CloudOnce __v2.4.0__
- Unity3D __v5.6.3__
- Build platform: Editor

**Comment by jizc** [comment]
After a quick test, it appears to be working (at least in the Unity editor). Perhaps we are expecting the method to do different things?

Could you describe the expected behavior, and what specifically is not working?

**Comment by PixelEnvision** [comment]
Thanks for the reply.

This is a clean project just with cloudonce.

I have currency int var "coins", it's set to 3 (both localy & on cloud) and there is a text on screen in Update() which shows current value.

When I call Cloud.Storage.DeleteAll (), it's value is set to 0. and next time I run the app (after removing it first) it's still 0.

When I call Cloud.Storage.DeleteVariable("coins"), value on screen stays at 3 and  also next time I run the app (after removing it first) it's still 3 so the key/value is still there.

Could it be specific to this value type?

**Comment by jizc** [comment]
Ah, I see. The problem there is that the `DeleteVariable` method is not intended to be used with a variable that is in use. I can see that this is not very clear. It's meant to be used to remove specific unused data in existing cloud data, like if you stop using a key, and you want to remove it from your users data.

It sounds like the method you want is the `PersistentCurrency.Reset` method. However this can only really be accessed if you set up your cloud variables manually (described in the [Advanced implementation](http://jizc.github.io/CloudOnce/gettingStarted.html#cloud-save-impl) section of the Getting Started guide).

To make this more practical I can add a `ResetVariable("key")` method to `Cloud.Storage`. Does this sound like it would solve your issue?

Btw the reason `DeleteAll` worked, is that that method also resets all variables that are in use.

**Comment by PixelEnvision** [comment]
Ah thanks for the explanation.

Yes, that would solve it but nothing urgent, I can also use the reset method.

Btw, on another subject.

As my next game will support tvos I'm currently checking if enabling tvos something I can do. I've added UNITY_TVOS everywhere it has UNITY_IOS and enabled plugins for tvos. So far it seems to work, I've got game center login dislayed and it seems to load cloud values. But it cannot read from existing ios key.

What I'd like to ask is, are there any ios specific sections in the plugin files? (..m)

**Comment by jizc** [comment]
Great, then I'll add it the next time I'm working on the plug-in. I'll leave this issue open to remind me.

To my knowledge, nothing in the plugin files should be iOS specific. It would be cool though if you manage to get it working!

**Comment by PixelEnvision** [comment]
That would be great, thanks.

And it's working on Apply TV :) I can confirm cloud save is working as expected and KVS syncs between iOS & tvOS both ways. Gamecenter login also works but I haven't tested all the functions yet such as player info, leaderboard overlay, etc.

As for the hack, all I did was:
1. Search & replace "UNITY_IOS" => "(UNITY_IOS || UNITY_TVOS)"
2. Mark all 4 files as TVOS compatible in unity file settings.

 I'll update the post once I'm confident there are no issues.

**Comment by jizc** [comment]
That's awesome, thank you for the update!

**Comment by PixelEnvision** [comment]
it works! :) Closing this as I'll post details in other Apple TV issue...
