### ISSUE TITLE
Leaderboard overlay not shown when using Leaderboards Button script

### ISSUE THREAD

**Issue by santins77** [jizc/CloudOnce#25]
## What steps will reproduce this issue?

Configure cloudonce only for android and using just leaderboards.
Autosign using Initialize Cloud Once script
Open leaderboard screen using Leaderboards Button script.

After those steps the leaderboards overlay is not shown and there is an error at logcat telling this:

09-27 15:09:47.718  8161  8188 I Unity   : Showing leaderboards overlay.
09-27 15:09:47.718  8161  8188 I Unity   :
09-27 15:09:47.718  8161  8188 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
09-27 15:09:47.718  8161  8188 I Unity   :
09-27 15:09:47.718  8161  8188 I Unity   :  [Play Games Plugin DLL] 09/27/17 15:09:47 +01:00 DEBUG: ShowLeaderboardUI, lbId= callback is System.Action`1[GooglePlayGames.BasicApi.UIStatus]
09-27 15:09:47.718  8161  8188 I Unity   :
09-27 15:09:47.718  8161  8188 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
09-27 15:09:47.718  8161  8188 I Unity   :
09-27 15:09:47.817  8161  8188 I Unity   :  [Play Games Plugin DLL] 09/27/17 15:09:47 +01:00 DEBUG: Showing UI Internal callback: ERROR_UI_BUSY

### Expected outcome

No error logcat and leaderboard overlay being shown

### Solution

When generating the AndroidManifest.xml for Google PLay Games include these lines:

        <activity android:name="com.google.games.bridge.NativeBridgeActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />

Those lines are not included at current version when clicking Run setup at CloudOnce editor screen.

--
### Environment

- CloudOnce __v2.4.2
- Unity3D __v5.6.1f1
- Build platform: Android

**Comment by jizc** [comment]
Thanks for the heads up. I know there was some changes to the template from Google in one of the last updates. Should be a quick fix.
