### ISSUE TITLE
Unity Collaborate doesn't sync CloudOnceSettings.txt

### ISSUE THREAD

**Issue by retNull** [jizc/CloudOnce#26]
## What steps will reproduce this issue?

Using the extremely limited Unity Collaborate as your version control.  Unity Collaborate seems to only sync changes in the Assets folder and CloudOnce stores it's settings in the ProjectSettings folder.

### Expected outcome

Synced CloudOnce settings across multiple computers.

--
### Environment

- CloudOnce __v2.4.3__
- Unity3D __v2017.1.f1__
- Build platform: Any

--
### Possible fixes

- Store CloudOnceSettings.txt somewhere in the Assets folder instead of ProjectSettings.
- Document issue with Collaborate in the readme

**Comment by jizc** [comment]
Thanks for the heads-up!

I'll think about a way to make it easier to choose the location of the settings. Perhaps a toggle in the CloudOnce Editor.

**Comment by retNull** [comment]
No problem. This is a great plugin and I'm happy to contribute as I'll be using it in all future projects.

I've tried updating Unity to 2017.2.0f3 in hopes that they updated Collaborate to search the ProjectSettings folder and they didn't.  For the time being, I've updated this line in CloudOncePaths.cs:

`public const string Settings = cloudOnce + "/CloudOnceSettings.txt";`

**Comment by jizc** [comment]
Release [v2.4.4](https://github.com/jizc/CloudOnce/releases/tag/v2.4.4) fixes this issue
