### ISSUE TITLE
Use lower version than play-services-base-11.0.4?

### ISSUE THREAD

**Issue by Whyser** [jizc/CloudOnce#27]
Hey man, nice work!
As you know, handling all the conflicts etc. with other plugins is a pain in the ass, as some plugin-makers don't follow the recommended approach (regarding GPGS). 
I'm wondering if it's possible to use this with a GPGS version of 9.8 instead of 11.0.4? I've tried changing the "10+" on every place I could find, but it still  somehow request that I use 11.0.4 with the error:

`ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-base:[11.0.4]`

Edit: I manage to resolve the issue by updating the GooglePlayResolver, but my questions kinda remain. Will I be able to use the Save feature if I depend on the GPGS 9.8.0 version? Thanks!

**Comment by jizc** [comment]
As far as I know there should be no issues using CloudOnce with an older version of GPGS, as long as the modifications I've done to GPGS stay (mainly the OnAuthenticated event).

**Comment by Whyser** [comment]
Thanks, I will try it out then!
