### ISSUE TITLE
Values are wrong after switching Google Account 

### ISSUE THREAD

**Issue by flaboratorium** [jizc/CloudOnce#33]
## What steps will reproduce this issue?

Log into GPGS with one account, save your values. Log out. Log in with a second account. Load values. You will get the cloud data of the first account instead of the active one.

### Expected outcome

Get all cloud variables of the logged in account.

--
### Environment

- CloudOnce __v2.4.5__
- Unity3D __v2017.1.1p1__
- Build platform: 
Android

**Comment by jizc** [comment]
Yeah, this is more of a design flaw than a bug. All the cloud values are stored locally with Unity's PlayerPrefs system with a single key, no matter what user is logged in.

To address this issue the DataManager would need to be changed to use the logged in account as part of the PlayerPrefs key. I'll see if I have some time during the weekend to find a solution to this.

**Comment by flaboratorium** [comment]
correct, might be possible to add the provided gpgs id of the logged in user as prefix to the CloudOnceDevString. i already noticed the "ReplaceLocalDataWith" function in the data manager commented with "Only to be used when player has switched to a different account.", but it seems that function is not in use?

**Comment by jizc** [comment]
I believe `ReplaceLocalDataWith` is only used on iOS

**Comment by flaboratorium** [comment]
I am wondering if the unlocked achievements are also stored locally in the playerprefs, as they unlock automatically when the second user (who did not unlock the achievements by himself)  logs in.

**Comment by jizc** [comment]
The states of achievements are not saved. All achievements get downloaded as soon as you log in. My guess would be that since the second user got the first users data, the second user then fulfilled whatever requirement that was set for the achievements in question.

**Comment by flaboratorium** [comment]
In my testing environment i unlock the achievements just by calling the unlock achievement function by pressing a button. When i log out and switch to the other account the achievements gets unlocked for the second user without the button press.

**Comment by jizc** [comment]
I don't know what would cause that. I'll have to take a closer look at it.

**Comment by flaboratorium** [comment]
Nice, thank you for the fast response, i did not expect this because cloud once was announced to have "no more support" in the unity forums ;)

**Comment by jizc** [comment]
I don't help with implementation, but I do want to fix bugs and make minor improvements :)

**Comment by flaboratorium** [comment]
Nice to know, would be great if this enhancement could be possible at sometime :) thanks!

**Comment by jizc** [comment]
I had a closer look at the `DataManager` issue, and it's a larger undertaking than I had anticipated. `DataManager.LoadFromDisk` is normally called before the player is logged in. So fixing this will require more than just adding a PlayerID prefix.

I also looked into the achievements issue, and I found the problem. This one should be easier to fix, as it should be solved be simply resetting the state of the local achievement instances before loading the new user's achievements.

I'll try to get to these issues tomorrow, but it may take a bit more time.

**Comment by flaboratorium** [comment]
Yes i was experimeting with the source code also and run into problems implementing the prefix solution ;) i personally have no urgent need to have this fixed quickly, but it would be really cool to have the account switch working in the future. thanks for having a look at it!

**Comment by jizc** [comment]
I've uploaded a new branch containing possible fixes for these issues. Both issues appear to be solved in my testing. But since these are significant changes, I would love it if you could test this release as well, before I merge with the master branch. New unitypackage: [CloudOnce-v2.4.6.unitypackage](https://github.com/jizc/CloudOnce/raw/development/current-build/CloudOnce-v2.4.6.unitypackage)

**Comment by flaboratorium** [comment]
Hey, i did a quick test in my sample project with the new version and everything seems to work perfectly now! i get the correct values of the different accounts from the cloud and even the achievement unlocks work as expected. Looks like you fixed that issue, very nice!!!

**Comment by jizc** [comment]
That's great! Thank you for testing :)

**Comment by flaboratorium** [comment]
You're welcome, Thanks for fixing it THAT QUICK!

**Comment by flaboratorium** [comment]
I tested it with two existing accounts which worked well, but i ran into another problem:
If i run the following script in the editor:

public class CloudTest : MonoBehaviour {

	void Start () {
        Cloud.OnInitializeComplete += InitializeCloudOnceComplete;
        Cloud.Initialize(true,false,false);
	}

    void InitializeCloudOnceComplete()
    {
        Cloud.OnInitializeComplete -= InitializeCloudOnceComplete;
        SignIn();
    }

    void SignIn()
    {
        Cloud.OnSignedInChanged += SignInComplete;
        Cloud.SignIn(false);
    }

    void SignInComplete(bool isSignedIn)
    {
        Cloud.OnSignedInChanged -= SignInComplete;
        Cloud.OnCloudLoadComplete += LoadComplete;
        Debug.Log(Cloud.PlayerID);
        Cloud.Storage.Load();
    }

    void LoadComplete(bool success)
    {
        Cloud.OnCloudLoadComplete -= LoadComplete;
        Debug.Log("LoadComplete() testValue: " + CloudVariables.testValue);
        CloudVariables.testValue = 10;
        Cloud.Storage.Save();
    }

}

First run: testValue = 0 which is ok because it did not exist at first
Second run : testValue = 0, but i should be 10 because in the last run i set it to 10

Am i missing something?

**Comment by jizc** [comment]
I seeing the same result, debugging now.

**Comment by flaboratorium** [comment]
Sorry missed that simple case, as said i tried it with two real google accounts on my device which worked well ^^

**Comment by jizc** [comment]
I'm definitely surprised both of us missed it first time round, but no worries, I'm testing a fix now :)

**Comment by jizc** [comment]
It should be fixed now. You'll find a [new unitypackage](https://github.com/jizc/CloudOnce/raw/master/current-build/CloudOnce-v2.4.6.unitypackage) in the [current-build](https://github.com/jizc/CloudOnce/tree/master/current-build) folder.

Thanks again for reporting bugs! ❤️

**Comment by flaboratorium** [comment]
Cool, yes, it works as expected now :) Thanks again! Just want to add that CloudOnce is the best Solution for me, setup was a breeze and you did a great job creating this Editor Window.
