### ISSUE TITLE
Cloud.OnSignedInChanged not being called on iOS

### ISSUE THREAD

**Issue by Whyser** [jizc/CloudOnce#34]
It seems the event: `Cloud.OnSignedInChanged` is not being called on iOS (works as expected on Android). 
I'm not sure if this is intended or not (since you don't really login on iOS, but it would make sense for the event to be called with "true" to mirror the behavior on iOS and Android). 
Can someone confirm?

**Comment by jizc** [comment]
It's called on [line 170 in iOSCloudProvider.cs](https://github.com/jizc/CloudOnce/blob/master/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs#L170)
