### ISSUE TITLE
Save only to local disk

### ISSUE THREAD

**Issue by d4rwins** [jizc/CloudOnce#39]
# **Enchancement**
Can we get a function in 

> Cloud.Storage

That save only on local disk (because I can't just enable an disable Cloud.EnableCloudSave since it need to be reinitialized) ? Use Cloud.Storage.Save() will auto save it on the cloud, for a shop in a game, you want to save all purchases( saving online every purchase can make heavy traffic), 

So saving locally the purchases and pushing the save to the cloud on a finished level ( for example)

**Comment by jizc** [comment]
You can use the static method [`DataManager.SaveToDisk()`](https://github.com/jizc/CloudOnce/blob/e519ca897e4237879c8d78a0ce521af9a5371cc3/source/PluginDev/Assets/Extensions/CloudOnce/Internal/Data/DataManager.cs#L725).
