### ISSUE TITLE
Feature Request: tvOS support 

### ISSUE THREAD

**Issue by khachatur91** [jizc/CloudOnce#4]
Hi,

As far as I know CloudOnce does not support tvOS. If I'm right , are you going to add this feature?

Best regards,
Khachatur

**Comment by zynthar** [comment]
There are currently no plans to add tvOS support. I do not have the hardware I would need to test and develop it on. If anyone else wants to add it, I'll certainly consider accepting a pull request.

**Comment by saqsun** [comment]
Hi there,
We would like to add tvOS support but not me, nor @khachatur91 haven't any experience in unity plugin development. So if with your help we can figure it out it will be wonderful.

**Comment by sindrijo** [comment]
I need a side project to work in so I might look into this in the near future, will update here when I have have something.

**Comment by RoninGames** [comment]
Any update on this?

**Comment by jizc** [comment]
No, I'm afraid that unless someone with a tvOS device can do the development for this and submit a pull request, it's not likely to happen.

**Comment by PixelEnvision** [comment]
Hi @jizc 

Follow-up from my ticket. It works 100% with Apple TV (tvOS 10&11) :)

Changes I've made:
1. Search & replace: "UNITY_IOS" => "(UNITY_IOS || UNITY_TVOS)"
2. Mark all 4 files in Plugins/iOS as TvOS compatible in unity file settings

After building the project, in Xcode:
1. Open Images.xcassets
2. Right click and select Game Center -> New Apple TV Leaderboard
3. Select leaderboard(s) and set the identifier(s) to match your leaderboard id(s).
4. Add graphics to leaderboards

I've tested unlocking achievements, updating scores, cloud functions and all works including cloud sync between iOS & tVOS (both must have same bundle identifier to use same KVS).

Both Show Leaderboards & Show Achievements buttons are working too, taking you the same page with all leaderboards and achievement shown at once. But if you don't do above xCode setup, you'll end up with "No data available" screen instead.

Can you update the repo or do you prefer a pull request?

**Comment by PixelEnvision** [comment]
On a side note, when doing the search and replace, I think we can safely exclude GooglePlayGames & AmazonGameCirclePlugin folders, just the files&folders in CloudOnce should be enough. I'll test it tough...

**Comment by PixelEnvision** [comment]
Tested above and it's ok. As search and replace updates template files, generated code (ie CloudIDs.cs) also seems fine.

**Comment by jizc** [comment]
That's awesome @PixelEnvision! Thank you for the detailed instructions. I'll make the same changes and add your instructions to the Getting Started guide.

**Comment by PixelEnvision** [comment]
You're welcome :) Btw, those are the files I've changed.

<img width="1092" alt="untitled" src="https://user-images.githubusercontent.com/8680071/30661108-da49a858-9e3a-11e7-98ca-2e1cc85af279.png">
