### ISSUE TITLE
documentation page no exists any more

### ISSUE THREAD

**Issue by Hamed1984** [jizc/CloudOnce#6]
why documentation page not exists?

my save game variables on ICloud not saved and gets error. do you have any documentation to describe how to config icloud for cloudonce?

thanks

**Comment by jizc** [comment]
The documentation links where outdated because I recently moved the GitHub repository. Thanks for making me aware of the problem! I've fixed the links now.

For any further assistance, I would recommend [StackOverflow](http://stackoverflow.com/).
