### ISSUE TITLE
PlatformSupportsCloud returns false on Iphone 5

### ISSUE THREAD

**Issue by Hamed1984** [jizc/CloudOnce#7]
i am testing on Iphone 5 but this method returns false

private static bool PlatformSupportsCloud()
        {
            if (!s_platformChecked)
            {
#if !UNITY_EDITOR
                s_platformSupportsCloud = (SystemInfo.operatingSystem.Contains("iPhone OS")
                                         && !SystemInfo.operatingSystem.Contains("iPhone OS 3")
                                         && !SystemInfo.operatingSystem.Contains("iPhone OS 4"));
#else
                s_platformSupportsCloud = true;
#endif
                s_platformChecked = true;
            }

            return s_platformSupportsCloud;
        }

**Comment by jizc** [comment]
Ah OK, that check can really just be removed, as it's not really needed these days. I'll remove it in a future update, for now you can just make the method return true at all times.

**Comment by jizc** [comment]
Fixed in [v2.3.0](https://github.com/jizc/CloudOnce/releases/tag/v2.3.0).
