### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Acimaz** [jizc/CloudOnce#8]
Hey guys,

we are using your plugin and recently found out that unity is reporting errors regarding it.
We took a look into the code but couldnt really find out why it happens. We hope that you have an idea in how to fix it. We believe that this error is leading to a crash of the app because a lot of our users claim that their app doesnt start correctly.

Here is a screenshot of the crashreport on unity:

![cloudonce_error](https://cloud.githubusercontent.com/assets/3418387/19072027/4ed6dfc8-8a33-11e6-84f3-30c7ceb78aab.PNG)

Here is the same error in text format:
`Trollpants.CloudOnce.Internal.Providers.GooglePlayGamesCloudSaveWrapper.OnSavedGameOpenedForLoad (SavedGameRequestStatus status, ISavedGameMetadata game)
GooglePlayGames.Native.NativeSavedGameClient+<ToOnGameThread>c__AnonStorey2AA`2+<ToOnGameThread>c__AnonStorey2AB`2[GooglePlayGames.BasicApi.SavedGame.SavedGameRequestStatus,GooglePlayGames.BasicApi.SavedGame.ISavedGameMetadata].<>m__81 ()
GooglePlayGames.OurUtils.PlayGamesHelperObject.Update ()`

We hope that we can fix this issue with your help!
### Environment
- CloudOnce __v2.2.4
- Unity3D __v5.3.5p8
- Build platform: Android and iOS

**Comment by jizc** [comment]
I've never had that issue. After looking through the code, my best guess would be that your game is sometimes attempting to load cloud data before the user authentication is complete. So I'd check to see if when your initializing CloudOnce, and when the first Load is executed. If you'd like a quick fix, add a null check in the OnSavedGameOpenedForLoad method.
