### ISSUE TITLE
Crash At Google Play Login on Android 6.0+

### ISSUE THREAD

**Issue by TinRobotStudios** [jizc/CloudOnce#9]
My App crashes when the google play login prompt drops in from the top.
Occurs on Android 6/7, I have yet to see it on any other version.

Debug spew points at this...

java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console
Exception in com/google/android/gms/games/snapshot/Snapshots.load: java.lang.IllegalStateException: Cannot use snapshots without enabling the 'Saved Game' feature in the Play console.

10-25 12:50:24.038: W/System.err(3762): java.lang.SecurityException: Not signed in when calling API
10-25 12:50:24.039: W/System.err(3762):     at com.google.android.gms.games.service.PlayGamesServiceBroker$GamesService.checkIsSignedIn(PlayGamesServiceBroker.java:679)
10-25 12:50:24.039: W/System.err(3762):     at com.google.android.gms.games.service.PlayGamesServiceBroker$GamesService.loadAchievementsV2(PlayGamesServiceBroker.java:851)
10-25 12:50:24.039: W/System.err(3762):     at com.google.android.gms.games.internal.IGamesService$Stub.onTransact(IGamesService.java:872)
10-25 12:50:24.039: W/System.err(3762):     at android.os.Binder.execTransact(Binder.java:458)
10-25 12:50:24.040: E/GamesNativeSDK(12385): Exception in com/google/android/gms/games/achievement/Achievements.load: java.lang.SecurityException: Not signed in when calling API.
10-25 12:50:24.042: W/GamesNativeSDK(12385): Could not automatically seed snapshot cache.
10-25 12:50:24.042: E/art(12385): JNI DETECTED ERROR IN APPLICATION: obj == null
10-25 12:50:24.042: E/art(12385):     in call to CallVoidMethodV
10-25 12:50:24.042: E/art(12385): "main_dispatch" prio=5 tid=36 Runnable
10-25 12:50:24.042: E/art(12385):   | group="main" sCount=0 dsCount=0 obj=0x12ebf100 self=0xb9f219b8
10-25 12:50:24.042: E/art(12385):   | sysTid=12498 nice=0 cgrp=default sched=0/0 handle=0x98ba8930
10-25 12:50:24.042: E/art(12385):   | state=R schedstat=( 11739614 10192617 38 ) utm=1 stm=0 core=3 HZ=100
10-25 12:50:24.042: E/art(12385):   | stack=0x98aac000-0x98aae000 stackSize=1014KB
10-25 12:50:24.042: E/art(12385):   | held mutexes= "mutator lock"(shared held)
10-25 12:50:24.042: E/art(12385):   (no managed stack frames)
10-25 12:50:24.043: A/art(12385): art/runtime/java_vm_ext.cc:441] JNI DETECTED ERROR IN APPLICATION: obj == null
10-25 12:50:24.043: A/art(12385): art/runtime/java_vm_ext.cc:441]     in call to CallVoidMethodV
10-25 12:50:24.043: A/art(12385): art/runtime/java_vm_ext.cc:441] "main_dispatch" prio=5 tid=36 Runnable
10-25 12:50:24.043: A/art(12385): art/runtime/java_vm_ext.cc:441]   | group="main" sCount=0 dsCount=0 obj=0x12ebf100 self=0xb9f219b8
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441]   | sysTid=12498 nice=0 cgrp=default sched=0/0 handle=0x98ba8930
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441]   | state=R schedstat=( 11739614 10192617 38 ) utm=1 stm=0 core=3 HZ=100
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441]   | stack=0x98aac000-0x98aae000 stackSize=1014KB
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441]   | held mutexes= "mutator lock"(shared held)
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441]   (no managed stack frames)
10-25 12:50:24.044: A/art(12385): art/runtime/java_vm_ext.cc:441] 

Google answers suggest that I haven't enabled this on dev console, but I have. Must re-iterate it has been tested quite a bit with no issues over several weeks and was formally released on 20th October.

Since then and because of this crash, I have had to pull the title from the play store.

Not sure this is related to Cloud Once itself or Google Play. I am suspecting (with no real backup) that I may be missing some config settings which have become necessary on Android 6/7.

Any advice appreciated!
- CloudOnce __v2.3.1
- Unity3D __v5.4.1.p4
- Build platform: Android

**Comment by jizc** [comment]
You are right that this is normally caused by attempting to initialize GPGS with the Saved Games feature before (or soon after) enabling it in the dev console. However since you can be sure that is not the issue here, I don't know what else can cause it.

Any chance you are not using the latest required libraries from the Android SDK?

I checked the repo of the GPGS plug-in and I can't find any new config needed. In CloudOnce, GPGS is initialized here: [GooglePlayGamesCloudProvider.cs#L155](https://github.com/jizc/CloudOnce/blob/master/source/PluginDev/Assets/Extensions/CloudOnce/Providers/GooglePlayGames/GooglePlayGamesCloudProvider.cs#L155). You can see Google's configuration instructions here: [Configuration & Initialization Play Game Services](https://github.com/playgameservices/play-games-plugin-for-unity#configuration--initialization-play-game-services).

Sorry to hear about your troubles, but it looks to me that this is an issue with the GPGS plug-in, not CloudOnce specifically. I see you have registered an Issue over on the GPGS repo, hopefully that will be more fruitful!

**Comment by TinRobotStudios** [comment]
Thanks Jan. I have a repro device now, so will have a look tonight and let
you know how I get on. Current thinking around work is that it's a timing
issue.... Trying to load before authentication has completed. Thanks again.
dave

**Comment by TinRobotStudios** [comment]
I have been looking into this a bit further tonight and have created a tiny project using latest cloud once and just a single object with the included 'Initialise Cloud Once' script attached. (Cloud save, auto sign in and auto cloud load all on)
On my trust old nexus 4 there is no problem.
On the Xperia 5 I have borrowed (where my app doesn't run) it prompts me to "Update Google Play services...xxx won't run unless you update Google Play Services"
I guess this probably has something to do with it.

I am running with cloudonce v2.3.1, Unity 5.4.2.p1 and the Xperia has Play games Version 3.7.23(2867637-036) and Android 6.0.

I am resisting allowing it to updata the Play Games version until I can get this message in my proper app. Then I will let it update and see if that fixes it.

Any thoughts?

btw. I tried messing with the timing (authentication, save loads etc - no joy)

**Comment by sindrijo** [comment]
@TinRobotStudios You could try running the [SmokeTest](https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/SmokeTest) sample from GPGS repo on the Xperia 5 to determine if it is an issue with CloudOnce, specific to the device or version of Google Play Services or Google Play Games. All the GPGS features are testable in that sample, including saved games.

The current available version of [Google Play Games on Google Play](https://play.google.com/store/apps/details?id=com.google.android.play.games) and Google Play Services varies between devices.

[Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms) is a 'core' app in Android and should be kept up to date. What version of Google Play services is the Nexus device running?

**Comment by TinRobotStudios** [comment]
Thanks @sindrijo sindrijo. I may give that a go.
@jizc 
An update....
I updated all the latest Google SDKs, upgraded to Unity 5.4.2.p1 and created a new empty project and added latest CloudOnce.

Hooked up to my live project....everything works!
So I slowly started adding everything back in and it broke again at the point I enabled the Unity services I need for my app - Analytics, iAP and Ads. Same crash, moaning about me not having enabled save on the google developer console.

:-( Only on Xperia...Nexus 4 is fine.

I am currently turning off cloud save to just get something back out there!!!
Once I have done that I am going to see if its possible to delay the Unity Services until after the cloud once initialisation, or vice versa.

I will keep you informed

btw....I had to juggle some folders around else the 'Run Setup' button didn't work.....

Move
Assets\Extensions\CloudOnce\Internal\Data\Editor\Utils
To
\Assets\Extensions\CloudOnce\Internal\Editor\Utils

Cheers

Dave

**Comment by jizc** [comment]
Thanks for the update. Glad to hear you're making progress! I'll be sure to check the `Run Setup` button. There have been some major changes to the project lately and I may have accidentally broken that ;)

**Comment by TinRobotStudios** [comment]
Quick question.....If I don't use cloud save by calling Cloud.Initialize(false,true,false), do I still get local saves?

**Comment by TinRobotStudios** [comment]
Jan is it possible DM?

**Comment by jizc** [comment]
Yes it will still save locally. I'm afraid I'm going to bed now ;)

**Comment by TinRobotStudios** [comment]
Cheers Buddy....seems to be working enough for me to throw out a new version. Will keep you posted on my progress. Sleep tight ;-)
